# Generated by Django 4.1.2 on 2022-10-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_profile_alter_address_client_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.profile', unique=True),
        ),
    ]
