# Generated by Django 4.1.2 on 2022-10-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
        ('clients', '0003_alter_client_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='shopping.shoppingcart', unique=True),
        ),
    ]
