# Generated by Django 4.1.2 on 2022-10-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cart',
        ),
    ]
