# Generated by Django 4.1.2 on 2022-10-17 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_shoppingcart_product_alter_shoppingcart_id'),
        ('clients', '0007_rename_client_client_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='shopping.shoppingcart', unique=True),
        ),
    ]
