# Generated by Django 4.1.2 on 2022-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_shoppingcart_product_alter_shoppingcart_id'),
        ('products', '0004_productcategory_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ManyToManyField(related_name='product_cart', to='shopping.shoppingcart'),
        ),
    ]
