# Generated by Django 4.1.2 on 2022-10-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='cart',
        ),
    ]
