# Generated by Django 4.1.2 on 2022-10-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_shoppingcart_product_alter_shoppingcart_id'),
        ('products', '0006_rename_product_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(related_name='products', to='shopping.shoppingcart'),
        ),
    ]
